name: Sync HuggingFace Backend

on:
workflow_dispatch:
schedule:
- cron: "0 0 * * *"

jobs:
sync:
runs-on: ubuntu-latest

```
steps:
  - name: Checkout Repo
    uses: actions/checkout@v4

  - name: Clone HF Space
    run: |
      git clone https://huggingface.co/spaces/Arko007/maritime hf-backend

  - name: Replace backend folder
    run: |
      rm -rf backend/*
      cp -r hf-backend/* backend/

  - name: Clean .git
    run: |
      rm -rf backend/.git

  - name: Commit & Push
    run: |
      git config --global user.name "github-actions"
      git config --global user.email "actions@github.com"
      git add backend
      git commit -m "Auto sync backend from HF" || echo "No changes"
      git push
```
